apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: statefulset-dynamicstorage
  namespace: episode5
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
